/* Automatically generated by create_config - do not modify */
#define CONFIG_QEMU_PREFIX "c:/Program Files/Qemu"
#define CONFIG_QEMU_BINDIR "c:/Program Files/Qemu"
#define CONFIG_QEMU_MANDIR "c:/Program Files/Qemu"
#define CONFIG_QEMU_DATADIR "c:/Program Files/Qemu"
#define CONFIG_QEMU_SYSCONFDIR "c:/Program Files/Qemu"
#define CONFIG_QEMU_DOCDIR "c:/Program Files/Qemu"
#define CONFIG_QEMU_CONFDIR "c:/Program Files/Qemu"
#define HOST_I386 1
#define HOST_LONG_BITS 32
#define CONFIG_WIN32 1
#define CONFIG_FILEVERSION 0,14,50-s5l89xx,0
#define CONFIG_PRODUCTVERSION 0,14,50-s5l89xx,0
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define CONFIG_HDA 1
#define CONFIG_AUDIO_DRIVERS \
    &winwave_audio_driver,\

#define CONFIG_WINWAVE 1
#define CONFIG_AUDIO_WIN_INT 1
#define CONFIG_BDRV_WHITELIST \
    NULL
#define CONFIG_VNC 1
#define CONFIG_VNC_JPEG 1
#define CONFIG_VNC_PNG 1
#define QEMU_VERSION "0.14.50-s5l89xx"
#define QEMU_PKGVERSION ""
#define CONFIG_SDL 1
#define CONFIG_GCC_ATTRIBUTE_WARN_UNUSED_RESULT 1
#define CONFIG_SKINNING 1
#define CONFIG_SMARTCARD 1
#define CONFIG_UNAME_RELEASE ""
#define CONFIG_ZERO_MALLOC 1
#define CONFIG_TRACE_FILE trace
