# Automatically generated by configure - do not modify
SRC_PATH=/home/Entr0py/qemu-ipad/roms/vgabios
CC=i686-w64-mingw32-gcc
BCC=bcc
CPP=i686-w64-mingw32-cpp
OBJCOPY=objcopy
IASL=iasl
LD=i686-w64-mingw32-ld
